apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pipeline-run-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  serviceAccountName: pipeline  # <--- THIS IS THE MISSING KEY
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: repo-url
      value: https://github.com/vinay123b/ci-cd-final-project
    - name: app-name
      value: ci-cd-final-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/sn-labs-ganapathiraj/ci-cd-final