apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: repo-url
    - name: app-name
    - name: build-image
  tasks:
    - name: cleanup
      taskRef: {name: cleanup}
      workspaces: [{name: source, workspace: source}]

    - name: git-clone
      taskRef: {name: git-clone}
      runAfter: [cleanup]
      workspaces: [{name: output, workspace: source}]
      params:
        - name: url
          value: $(params.repo-url)

    - name: flake8
      taskRef: {name: flake8}
      runAfter: [git-clone]
      workspaces: [{name: source, workspace: source}]

    - name: nose
      taskRef: {name: nose}
      runAfter: [flake8]
      workspaces: [{name: source, workspace: source}]

    - name: buildah
      taskRef: {name: buildah}
      runAfter: [nose]
      workspaces: [{name: source, workspace: source}]
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef: {name: openshift-client}
      runAfter: [buildah]
      params:
        - name: SCRIPT
          value: oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -